name: Python application

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10']

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get -qq update
          sudo apt-get install -y libemail-outlook-message-perl
          pip install ".[dev, test]"
          export PERL_MM_USE_DEFAULT=1
          sudo cpan -f -i Email::Outlook::Message

      - name: Run tests
        env:
          PYTHONPATH: src
        run: |
          pytest --cov=mailparser --cov-report=xml
          python -m mailparser -v
          python -m mailparser -h
          mail-parser -f tests/mails/mail_malformed_3 -j
          cat tests/mails/mail_malformed_3 | mail-parser -k -j

      - name: Run pre-commit
        if: matrix.python-version == '3.10'
        run: |
          make pre-commit

      - name: Report to Coveralls
        if: matrix.python-version == '3.10'
        uses: coverallsapp/github-action@v2.2.3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        if: matrix.python-version == '3.10'
        run: |
          python -m build

      - name: Upload artifacts
        if: matrix.python-version == '3.10'
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            dist/mail-parser-*.tar.gz
            dist/mail_parser-*.whl

  docker:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract branch or tag name
        id: extract_ref
        run: |
          if [ -n "${GITHUB_HEAD_REF}" ]; then
            REF_NAME=${GITHUB_HEAD_REF}
          else
            REF_NAME=$(git describe --tags --exact-match 2>/dev/null || git rev-parse --abbrev-ref HEAD)
          fi
          echo "REF_NAME=${REF_NAME,,}" >> $GITHUB_ENV

      - name: Debug REF_NAME
        run: echo "REF_NAME=${{ env.REF_NAME }}"

      - name: Build and push Docker image
        run: |
          cd docker
          IMAGE_NAME=ghcr.io/ghcr.io/spamscope/mail-parser/mailparser
          docker build \
            --label "org.opencontainers.image.source=${{ github.repositoryUrl }}" \
            --label "org.opencontainers.image.description=Easy way to pass from raw mail to Python object" \
            --label "org.opencontainers.image.licenses=Apache-2.0" \
            --build-arg BRANCH=${{ env.REF_NAME }} \
            -t $IMAGE_NAME:${{ env.REF_NAME }} .
          docker push $IMAGE_NAME:${{ env.REF_NAME }}
